export const DATA_TYPES = {
  GET_DASHBOARD_STATISTICS_DATA: "GET_DASHBOARD_STATISTICS_DATA",
  GET_DASHBOARD_USER_LIST: "GET_DASHBOARD_USER_LIST",
  UPDATE_PAGENUMBER: "UPDATE_PAGENUMBER",
};

export const UI_TYPES = {
  OPEN_OVERLAY:"OPEN_OVERLAY",
  CLOSE_OVERLAY:"CLOSE_OVERLAY",
  LOADING:"LOADING",
  STOP_LOADING:"STOP_LOADING",
};

export const FORM_TYPES = {
  NEW_FORM:"NEW_FORM", 
  UPDATE_FORM:"UPDATE_FORM", 
}